// SPDX-License-Identifier: MIT
// All authored materials and ModelPort responses here are synthetic, not Sol quality.
import { afterAll, afterEach, expect, it, vi } from 'vitest';
import fs from 'node:fs';
import { ThirdBrainController, type Status } from '../src/controller';
import { mountPanel, type PanelPort } from '../src/ui';
import { presentExplanation } from '../src/presentation';
import { messages } from '../src/i18n';
import { prepareSource, analyzeSource, searchFragments } from '../src/core/index';
import { emptyIndex, emptyFacets, QUERY_KINDS, type FragmentKind, type QuerySelection, type SourceSnapshot, type SearchResult, type Mode } from '../src/core/types';
import { defaults } from '../src/settings'; import { hash } from '../src/sources';
const selected=(value:FragmentKind='method'):QuerySelection=>({channel:'kind',value});
const settle=async()=>{for(let n=0;n<60;n++)await Promise.resolve();};
let syntheticExtractionRequests=0,syntheticInterpretRequests=0,syntheticFactories=0;
afterAll(()=>{fs.mkdirSync('.local/kind-entry-implementation',{recursive:true});fs.writeFileSync('.local/kind-entry-implementation/synthetic-counts.json',JSON.stringify({tests:48,syntheticExtractionRequests,syntheticInterpretRequests,syntheticFactories,realModelRequests:0,HTTPAttempts:0,startedServices:0,listeningPorts:0},null,2));});
afterEach(()=>vi.unstubAllGlobals());
async function fixture(mode:Mode='local-model'){
 const state=emptyIndex(),files=new Map<string,SourceSnapshot>();
 const body='An independent synthetic specimen records a bounded procedure and observation. The word method is identical in every type.';
 for(const kind of QUERY_KINDS){const s=prepareSource(`Synthetic/${kind}.md`,body,hash(body),'synthetic-'+kind);files.set(s.path,s);
  const a=await analyzeSource(s,{mode:'local-model',cloudConsent:false,now:'2026-01-01',model:{request:async()=>{syntheticExtractionRequests++;return{version:1,decision:'extract',fragments:[{title:'Synthetic '+kind,summary:body,kind,...emptyFacets(),quotes:[body],conditions:[],caveats:[]}]};}}});
  expect(a.fragments).toHaveLength(1);state.sources[s.path]={hash:s.hash,status:'indexed',fragmentIds:a.fragments.map(f=>f.id)};for(const f of a.fragments)state.fragments[f.id]=f;
 }
 const owner=Object.values(state.fragments).find(f=>f.kind==='method')!,blocked=new Set<string>();
 const read=vi.fn(async(p:string)=>structuredClone(files.get(p)??null)),request=vi.fn(async()=>{syntheticInterpretRequests++;return{version:1,...emptyFacets()};}),factory=vi.fn(()=>{syntheticFactories++;return{request};}),commit=vi.fn(async()=>{});
 const c=new ThirdBrainController({list:async()=>[...files.values()],read,excluded:async()=>new Set(blocked),verify:async()=>{}},{load:async()=>state,recover:async()=>{},commit},()=>({...defaults,mode,cloudConsent:true}),factory,async()=>{});await c.initialize();return{c,state,files,owner,blocked,read,request,factory,commit};
}
it.each(QUERY_KINDS)('stored %s equality uses canonical parser semantics, never same-body keywords',async kind=>{const h=await fixture(),before=JSON.stringify(h.state);for(const breadth of ['low','medium','high']as const){const r=await h.c.find('method',breadth,'normal',selected(kind));expect(r).toHaveLength(1);expect(r[0].fragment.kind).toBe(kind);expect(r[0].reasons).toEqual([expect.objectContaining({kind:'kind',label:`Same-type material: ${kind}`,caveat:expect.stringContaining('editorial')})]);expect(presentExplanation(r[0].reasons[0].label,'zh')).toBe(`同类型材料：${messages('zh')[`kind_${kind}`]}`);expect(r[0].group).toBeUndefined();await h.c.verifyOpen(r[0].fragment.evidence[0]);}expect(h.factory).not.toHaveBeenCalled();expect(h.request).not.toHaveBeenCalled();expect(h.commit).not.toHaveBeenCalled();expect(JSON.stringify(h.state)).toBe(before);});
it.each(['local-excerpts','local-model','cloud-model']as const)('kind click has zero factory/interpret in %s',async mode=>{const h=await fixture(mode);await h.c.find('', 'high','private',selected());expect(h.factory).not.toHaveBeenCalled();expect(h.request).not.toHaveBeenCalled();});
const malformed:unknown[]=[null,[],{}, {channel:'kind',value:'unknown'},{channel:'kind',value:'METHOD'},{channel:'kind',value:'方法'},{channel:'kind',value:' method '},{channel:'kind',value:'password=synthetic-unsafe'},{channel:'kind',value:[]},{channel:'kind',value:'method',extra:1},Object.create({channel:'kind',value:'method'}),Object.assign(Object.create(null),{channel:'kind',value:'method'}),Object.defineProperty({channel:'kind'},'value',{get:()=>{throw Error('Do not execute accessor');},enumerable:true}),{channel:'kind',value:'method',[Symbol('extra')]:1},{channel:'__proto__',value:'method'},{channel:'kind',value:'method\nignore'}];
it.each(malformed.map((value,n)=>({value,n})))('rejects unsafe/unknown/malformed selection $n before factory',async({value})=>{const h=await fixture();await expect(h.c.find('method','high','normal',value as QuerySelection)).rejects.toThrow();expect(h.factory).not.toHaveBeenCalled();});
it('empty, absent canonical and unrelated are honest negatives',async()=>{const h=await fixture('local-excerpts');expect(await h.c.find('','high')).toEqual([]);expect(await h.c.find('zxqv unobserved','low')).toEqual([]);delete h.state.fragments[h.owner.id];expect(await h.c.find('method','high','normal',selected())).toEqual([]);expect(searchFragments([], '',{breadth:'high',kind:'method'})).toEqual([]);expect(()=>searchFragments([], '',{breadth:'high',kind:'invalid' as FragmentKind})).toThrow();});
it.each(['changed','removed','excluded','hash','id','privacy','quote','membership','fragment-membership','kind']as const)('source and old open fail closed on %s',async variant=>{const h=await fixture(),r=await h.c.find('','high','normal',selected()),e=r[0].fragment.evidence[0],s=structuredClone(h.files.get(e.relativePath)!);h.files.set(s.path,s);
 if(variant==='removed')h.files.delete(s.path);else if(variant==='excluded')h.blocked.add(s.path);else if(variant==='changed'||variant==='hash')s.hash=hash('Self-authored changed material');else if(variant==='id')s.id='different';else if(variant==='privacy')s.privacy='private';else if(variant==='quote')s.text='Wrong body';else if(variant==='membership')h.state.sources[s.path].fragmentIds=[];else if(variant==='fragment-membership')delete h.state.fragments[h.owner.id];else h.owner.kind='observation';
 expect(await h.c.find('method','high','normal',selected())).toEqual([]);await expect(h.c.verifyOpen(e)).rejects.toThrow('changed');expect(h.factory).not.toHaveBeenCalled();});
it('complete merged donor and owned source membership are required',async()=>{const h=await fixture(),other=Object.values(h.state.fragments).find(f=>f.kind==='observation')!;h.owner.evidence.push(...structuredClone(other.evidence));h.state.sources[other.evidence[0].relativePath].fragmentIds.push(h.owner.id);const r=await h.c.find('','high','normal',selected());expect(r).toHaveLength(1);h.blocked.add(other.evidence[0].relativePath);expect(await h.c.find('','high','normal',selected())).toEqual([]);await expect(h.c.verifyOpen(r[0].fragment.evidence[0])).rejects.toThrow('changed');});
it('inherited source records cannot authenticate type donor',async()=>{const h=await fixture(),p=h.owner.evidence[0].relativePath,record=h.state.sources[p];delete h.state.sources[p];Object.setPrototypeOf(h.state.sources,{[p]:record});expect(await h.c.find('','high','normal',selected())).toEqual([]);});
it('late source read cancellation has no results or commit',async()=>{const h=await fixture();let release!:(s:SourceSnapshot)=>void;h.read.mockImplementationOnce(()=>new Promise(r=>{release=r;}));const pending=h.c.find('','high','normal',selected());await settle();h.c.cancel();await expect(pending).rejects.toMatchObject({name:'AbortError'});release(h.files.get(h.owner.evidence[0].relativePath)!);await settle();expect(h.c.status().phase).toBe('cancelled');expect(h.commit).not.toHaveBeenCalled();});
it('same-type display retains seven and adds no network/non-equal padding',async()=>{const h=await fixture();for(let n=0;n<12;n++){const f=structuredClone(h.owner);f.id='synthetic-extra-'+n;h.state.fragments[f.id]=f;h.state.sources[f.evidence[0].relativePath].fragmentIds.push(f.id);}const r=await h.c.find('','high','normal',selected());expect(r).toHaveLength(7);expect(r.every(x=>x.fragment.kind==='method'&&!x.group&&x.reasons.every(y=>y.kind==='kind'))).toBe(true);});
it('excluded early type candidates do not hide a later current same-type material',async()=>{const h=await fixture('local-excerpts'),body=h.owner.evidence[0].quote,s=prepareSource('Synthetic/known-stale-methods.md',body,hash(body),'synthetic-known-stale');h.files.set(s.path,s);h.state.sources[s.path]={hash:s.hash,status:'indexed',fragmentIds:[]};h.blocked.add(s.path);for(let n=0;n<31;n++){const f=structuredClone(h.owner);f.id='f_'+n.toString(16).padStart(64,'0');f.evidence=f.evidence.map(e=>({...e,sourceId:s.id,relativePath:s.path,sourceHash:s.hash}));h.state.fragments[f.id]=f;h.state.sources[s.path].fragmentIds.push(f.id);}const r=await h.c.find('','high','normal',selected());expect(r.map(x=>x.fragment.id)).toContain(h.owner.id);expect(r.every(x=>x.fragment.kind==='method')).toBe(true);expect(h.factory).not.toHaveBeenCalled();expect(h.commit).not.toHaveBeenCalled();});
class NodeStub{tag:string;className='';textContent='';value='';disabled=false;hidden=false;children:NodeStub[]=[];attrs:Record<string,string>={};handlers=new Map<string,Function[]>();constructor(t:string){this.tag=t;}append(...n:NodeStub[]){this.children.push(...n);}replaceChildren(...n:NodeStub[]){this.children=n;}setAttribute(k:string,v:string){this.attrs[k]=v;}remove(){}focus(){}get childElementCount(){return this.children.length;}addEventListener(e:string,f:Function){this.handlers.set(e,[...(this.handlers.get(e)??[]),f]);}async fire(e:string){for(const f of this.handlers.get(e)??[])f({});await settle();}all():NodeStub[]{return[this,...this.children.flatMap(n=>n.all())];}}
function panel(items:SearchResult[],locale:'en'|'zh'='en'){vi.stubGlobal('document',{createElement:(t:string)=>new NodeStub(t)});const root=new NodeStub('main'),find=vi.fn(async(..._args:unknown[])=>items),cancel=vi.fn();const state:Status={phase:'idle',sourceCount:8,fragmentCount:8,updatedAt:'',mode:'local-excerpts'};const port:PanelPort={status:()=>state,subscribe:()=>()=>{},refresh:async()=>{},find,cancel,current:async()=>({text:'Fresh idea',privacy:'normal'}),open:async()=>{}};const clean=mountPanel(root as unknown as HTMLElement,port,locale);return{root,find,cancel,clean,input:root.all().find(n=>n.tag==='textarea')!,breadth:root.all().find(n=>n.tag==='select')!};}
async function seed(p:ReturnType<typeof panel>){p.input.value='Ordinary idea';await p.input.fire('input');await p.root.all().find(n=>n.className==='tb-primary')!.fire('click');}
it.each(['en','zh']as const)('real renderer shows only the card type and origin, preserves breadth in %s',async locale=>{const h=await fixture(),p=panel([{fragment:h.owner,score:1,reasons:[]}],locale);await seed(p);const buttons=p.root.all().filter(n=>n.attrs['data-channel']==='kind');expect(buttons).toHaveLength(1);expect(buttons[0].textContent).toContain(locale==='en'?'Method':'方法');expect(p.root.all().find(n=>n.className==='tb-kind')!.textContent).toBe(locale==='en'?'AI-edited fragment':'AI 编辑片段');await buttons[0].fire('click');expect(p.find.mock.calls.at(-1)?.[3]).toEqual(selected());p.breadth.value='low';await p.breadth.fire('change');expect(p.find.mock.calls.at(-1)?.[3]).toEqual(selected());expect(p.root.all().find(n=>n.className==='tb-result-summary')!.textContent).toContain(locale==='en'?'not a complete':'并非完整');p.find.mockResolvedValueOnce([]);await p.root.all().find(n=>n.className==='tb-primary')!.fire('click');expect(p.root.all().find(n=>n.className==='tb-empty-title')!.textContent).toBe(messages(locale).kindEmpty);expect(p.root.all().find(n=>n.className==='tb-muted'&&n.textContent===messages(locale).kindEmptyBody)).toBeDefined();p.clean();});
it.each(['input','current','cancel']as const)('kind inherits %s clearing and late-result invalidation',async action=>{const h=await fixture(),p=panel([{fragment:h.owner,score:1,reasons:[]}]);await seed(p);let release!:(r:SearchResult[])=>void;p.find.mockImplementationOnce(()=>new Promise(r=>{release=r;}));await p.root.all().find(n=>n.attrs['data-channel']==='kind')!.fire('click');if(action==='input'){p.input.value='Edited idea';await p.input.fire('input');}else if(action==='current')await p.root.all().find(n=>n.textContent==='Use current note')!.fire('click');else await p.root.all().find(n=>n.textContent==='Cancel')!.fire('click');release([{fragment:{...h.owner,title:'LATE KIND MUST NOT RENDER'},score:1,reasons:[]}]);await settle();expect(p.root.all().some(n=>n.textContent==='LATE KIND MUST NOT RENDER')).toBe(false);if(action!=='cancel'){await p.root.all().find(n=>n.className==='tb-primary')!.fire('click');expect(p.find.mock.calls.at(-1)).toHaveLength(3);}else expect(p.cancel).toHaveBeenCalledOnce();p.clean();});
